import Foundation

struct AppLocalization {
    private static let strings: [String: [String: String]] = [
        "en": [
            "app.title": "Link2Download",
            "toolbar.paste": "Paste Link",
            "toolbar.settings": "Settings",
            "toolbar.about": "About",
            "toolbar.debug": "Debug report",
            "toolbar.smart": "Smart Mode",
            "toolbar.download": "Download",
            "toolbar.quality": "Quality",
            "toolbar.format": "Format",
            "toolbar.saveTo": "Save To",
            "toolbar.speed": "Speed",
            "toolbar.chooseFolder": "Choose",
            "toolbar.resetDefaults": "Reset Defaults",
            "toolbar.search": "Search by title, URL, creator",
            "toolbar.clearSearch": "Clear search",
            "toolbar.clearList": "Clear List",
            "toolbar.retryErrors": "Retry errors",
            "toolbar.clearErrors": "Clear errors",
            "toolbar.startHint": "Paste a supported link to start automatically.",
            "filter.all": "All",
            "filter.video": "Video",
            "filter.audio": "Audio",
            "stats.active": "Active",
            "stats.queued": "Queued",
            "stats.completed": "Completed",
            "stats.failed": "Failed",
            "empty.title": "No downloads yet",
            "empty.subtitle": "Paste a URL from YouTube, Vimeo, TikTok, or Instagram.",
            "empty.noResultsTitle": "Nothing found",
            "empty.noResultsSubtitle": "Try clearing search or switching filters.",
            "empty.action.resetFilters": "Reset filters",
            "empty.action.paste": "Paste link",
            "empty.action.settings": "Open settings",
            "row.status.queued": "Queued",
            "row.status.queuedDownload": "Queued for download",
            "row.status.queuedProcessing": "Queued for processing",
            "row.status.downloading": "Downloading",
            "row.status.processing": "Processing",
            "row.status.completed": "Completed",
            "row.status.failed": "Failed",
            "row.status.cancelled": "Cancelled",
            "row.status.cancelledHint": "Download was cancelled by user.",
            "progress.preparing": "Preparing download...",
            "progress.downloading": "Downloading...",
            "progress.finalizing": "Finalizing file...",
            "progress.appleOptimize": "Optimizing for Apple...",
            "progress.appleCopy": "Remuxing to Apple MOV...",
            "progress.appleHWTranscode": "Hardware transcoding for Apple MOV...",
            "progress.appleSWTranscode": "Software transcoding for Apple MOV...",
            "progress.cookiesRetry": "Retrying with browser cookies",
            "progress.section.download": "Download",
            "progress.section.processing": "Processing",
            "progress.stats.of": "of",
            "progress.stats.total": "Total:",
            "progress.stats.avg": "avg",
            "progress.stats.left": "left",
            "progress.stats.remaining": "left",
            "progress.stats.speed": "speed",
            "progress.stats.eta": "ETA",
            "stage.label": "Stage",
            "stage.preparing": "Preparing",
            "stage.downloading": "Download",
            "stage.remuxing": "Remux",
            "stage.hardwareTranscode": "Hardware transcode",
            "stage.softwareTranscode": "Software transcode",
            "action.showFinder": "Show in Finder",
            "action.openFile": "Open File",
            "action.copySource": "Copy Source URL",
            "action.openBrowser": "Open in Browser",
            "action.deleteFile": "Delete File",
            "action.cancel": "Cancel",
            "action.retry": "Retry",
            "action.transcodeCopy": "Transcode Copy",
            "action.more": "More",
            "action.removeFromList": "Remove from List",
            "details.source": "Source",
            "details.file": "File",
            "details.updated": "Updated",
            "details.originalBitrate": "Original bitrate",
            "details.transcodedBitrate": "Copy bitrate",
            "settings.title": "Preferences",
            "settings.language": "Language",
            "settings.system": "System",
            "settings.english": "English",
            "settings.russian": "Russian",
            "settings.hindi": "Hindi",
            "settings.chinese": "Chinese",
            "settings.kind": "Default Download Type",
            "settings.kind.video": "Video",
            "settings.kind.audio": "Audio",
            "settings.quality": "Default Quality",
            "settings.videoFormat": "Video Format",
            "settings.audioFormat": "Audio Format",
            "settings.path": "Default Save Folder",
            "settings.limit": "Speed Limit",
            "settings.transcodeBitrate": "Transcode Video Bitrate",
            "settings.appleTranscode": "Auto-convert to Apple MOV",
            "settings.appleTranscodeHelp": "When disabled, videos are saved without Apple MOV conversion. Faster and lower CPU load.",
            "settings.cookies": "Browser Cookies",
            "cookies.auto": "Auto",
            "cookies.none": "Disabled",
            "settings.youtubeAccessTitle": "YouTube Access",
            "settings.youtubeAccessBody": "Age-restricted and account-only YouTube videos need a signed-in browser session. Link2Download can reuse supported browser cookies, including Comet, when needed.",
            "settings.youtubeAccessAuto": "Auto first tries your default browser, then other installed supported browsers such as Comet, Chrome, Safari, Edge, Chromium, and Firefox.",
            "settings.youtubeAccessSelected": "Only the selected browser will be used for restricted YouTube videos.",
            "settings.youtubeAccessDisabled": "Browser cookies are disabled, so restricted YouTube videos will usually fail.",
            "settings.openYouTube": "Open YouTube",
            "settings.subtitles": "Download subtitles when available",
            "settings.audioTracks": "Download additional audio tracks when available",
            "settings.close": "Done",
            "about.title": "About Link2Download",
            "about.app": "Application",
            "about.version": "Version",
            "about.developer": "Developer",
            "about.website": "Website",
            "quality.smart": "Smart",
            "quality.best": "Best",
            "quality.720": "720p",
            "quality.1080": "1080p",
            "quality.4k": "4K",
            "quality.8k": "8K",
            "speed.unlimited": "Unlimited",
            "speed.50": "50 Mbps",
            "speed.25": "25 Mbps",
            "speed.10": "10 Mbps",
            "speed.4": "4 Mbps",
            "transcode.bitrate.auto": "Auto (high quality)",
            "toast.invalidURL": "Clipboard does not contain a valid URL.",
            "toast.alreadyQueued": "This link is already downloading or queued.",
            "toast.started": "Download started",
            "toast.debugCopied": "Debug report copied to clipboard. Paste it in chat.",
            "toast.debugFailed": "Failed to copy debug report to clipboard.",
            "toast.toolMissing": "Bundled yt-dlp/ffmpeg not found.",
            "toast.transcodeVideoOnly": "Transcoding is available only for video files.",
            "toast.transcodeSourceMissing": "Cannot find source file for transcoding.",
            "playlist.prompt.title": "This link is part of a playlist",
            "playlist.prompt.message": "Download only this video or the entire playlist?",
            "playlist.prompt.single": "Only this video",
            "playlist.prompt.all": "Entire playlist",
            "meta.durationUnknown": "duration unknown",
            "meta.noFile": "file pending",
            "meta.noSize": "size unknown",
            "meta.failed": "Operation failed",
            "error.vimeo.linkHint": "This Vimeo link cannot be opened directly. Try the embed/player link from Vimeo (player.vimeo.com/video/<id>?h=<token>).",
            "error.interruptedSession": "This job was interrupted when the app was restarted. Retry to continue.",
            "error.cookies.browserHint": "Link2Download could not read browser cookies for this request. Open YouTube in a supported browser such as Comet or Chrome, confirm you are signed in, then retry.",
            "error.youtube.authHint": "YouTube requires an authorized browser session for this video. Link2Download can use your browser cookies automatically. Make sure you are signed in to YouTube in Comet, Safari, Chrome, Edge, Chromium, or Firefox, then retry.",
            "error.youtube.formatHint": "YouTube exposed a restricted format list for this video. Link2Download already tried compatible fallbacks. If it still fails, switch the video format to MKV or retry with another browser profile.",
            "warn.subtitlesPartial": "Video downloaded, but subtitles were partially unavailable.",
            "smart.enabled": "Smart defaults are enabled.",
            "smart.disabled": "Manual settings are enabled.",
            "smart.help": "Smart mode picks the highest available quality from each source and auto-converts videos for Apple/Final Cut compatibility: best available stream -> Apple MOV.",
            "smart.profileHint": "Any service: best available quality -> Apple MOV.",
            "smart.profileHintNoTranscode": "Any service: best available quality -> source format (faster)."
        ],
        "ru": [
            "app.title": "Link2Download",
            "toolbar.paste": "Вставить ссылку",
            "toolbar.settings": "Настройки",
            "toolbar.about": "О приложении",
            "toolbar.debug": "Debug-лог",
            "toolbar.smart": "Умный режим",
            "toolbar.download": "Скачивать",
            "toolbar.quality": "Качество",
            "toolbar.format": "Формат",
            "toolbar.saveTo": "Сохранить в",
            "toolbar.speed": "Скорость",
            "toolbar.chooseFolder": "Выбрать",
            "toolbar.resetDefaults": "Сбросить по умолчанию",
            "toolbar.search": "Поиск по названию, ссылке, автору",
            "toolbar.clearSearch": "Очистить поиск",
            "toolbar.clearList": "Очистить список",
            "toolbar.retryErrors": "Повторить ошибки",
            "toolbar.clearErrors": "Убрать ошибки",
            "toolbar.startHint": "Вставьте поддерживаемую ссылку, чтобы загрузка началась автоматически.",
            "filter.all": "Все",
            "filter.video": "Видео",
            "filter.audio": "Аудио",
            "stats.active": "Активно",
            "stats.queued": "В очереди",
            "stats.completed": "Готово",
            "stats.failed": "Ошибки",
            "empty.title": "Пока нет загрузок",
            "empty.subtitle": "Вставьте URL с YouTube, Vimeo, TikTok или Instagram.",
            "empty.noResultsTitle": "Ничего не найдено",
            "empty.noResultsSubtitle": "Попробуйте сбросить поиск или фильтры.",
            "empty.action.resetFilters": "Сбросить фильтры",
            "empty.action.paste": "Вставить ссылку",
            "empty.action.settings": "Открыть настройки",
            "row.status.queued": "В очереди",
            "row.status.queuedDownload": "В очереди на скачивание",
            "row.status.queuedProcessing": "В очереди на обработку",
            "row.status.downloading": "Скачивается",
            "row.status.processing": "Обработка",
            "row.status.completed": "Готово",
            "row.status.failed": "Ошибка",
            "row.status.cancelled": "Отменено",
            "row.status.cancelledHint": "Загрузка была отменена пользователем.",
            "progress.preparing": "Подготовка загрузки...",
            "progress.downloading": "Скачивание...",
            "progress.finalizing": "Финальная обработка файла...",
            "progress.appleOptimize": "Оптимизация для Apple...",
            "progress.appleCopy": "Ремультиплексирование в Apple MOV...",
            "progress.appleHWTranscode": "Аппаратное перекодирование в Apple MOV...",
            "progress.appleSWTranscode": "Программное перекодирование в Apple MOV...",
            "progress.cookiesRetry": "Повтор с cookies браузера",
            "progress.section.download": "Скачивание",
            "progress.section.processing": "Обработка",
            "progress.stats.of": "из",
            "progress.stats.total": "Всего:",
            "progress.stats.avg": "ср.",
            "progress.stats.left": "осталось",
            "progress.stats.remaining": "осталось",
            "progress.stats.speed": "скорость",
            "progress.stats.eta": "ETA",
            "stage.label": "Этап",
            "stage.preparing": "Подготовка",
            "stage.downloading": "Скачивание",
            "stage.remuxing": "Ремультиплексирование",
            "stage.hardwareTranscode": "Аппаратное перекодирование",
            "stage.softwareTranscode": "Программное перекодирование",
            "action.showFinder": "Показать в Finder",
            "action.openFile": "Открыть файл",
            "action.copySource": "Скопировать адрес ссылки",
            "action.openBrowser": "Открыть ссылку в браузере",
            "action.deleteFile": "Удалить файл",
            "action.cancel": "Отменить",
            "action.retry": "Повторить",
            "action.transcodeCopy": "Транскодировать копию",
            "action.more": "Еще",
            "action.removeFromList": "Убрать из списка",
            "details.source": "Источник",
            "details.file": "Файл",
            "details.updated": "Обновлено",
            "details.originalBitrate": "Битрейт оригинала",
            "details.transcodedBitrate": "Битрейт копии",
            "settings.title": "Параметры",
            "settings.language": "Язык",
            "settings.system": "Системный",
            "settings.english": "Английский",
            "settings.russian": "Русский",
            "settings.hindi": "Hindi",
            "settings.chinese": "Китайский",
            "settings.kind": "Тип скачивания по умолчанию",
            "settings.kind.video": "Видео",
            "settings.kind.audio": "Аудио",
            "settings.quality": "Качество по умолчанию",
            "settings.videoFormat": "Формат видео",
            "settings.audioFormat": "Формат аудио",
            "settings.path": "Папка сохранения по умолчанию",
            "settings.limit": "Ограничение скорости",
            "settings.transcodeBitrate": "Битрейт видео при транскоде",
            "settings.appleTranscode": "Авто-конвертация в Apple MOV",
            "settings.appleTranscodeHelp": "Если отключить, видео сохраняется без конвертации в Apple MOV. Быстрее и меньше нагрузка на CPU.",
            "settings.cookies": "Cookies браузера",
            "cookies.auto": "Авто",
            "cookies.none": "Отключено",
            "settings.youtubeAccessTitle": "Доступ к YouTube",
            "settings.youtubeAccessBody": "Возрастные и некоторые закрытые ролики YouTube требуют авторизованную сессию браузера. Link2Download умеет использовать cookies поддерживаемых браузеров, включая Comet, когда это нужно.",
            "settings.youtubeAccessAuto": "Режим «Авто» сначала пробует браузер по умолчанию, затем другие установленные поддерживаемые браузеры, включая Comet, Chrome, Safari, Edge, Chromium и Firefox.",
            "settings.youtubeAccessSelected": "Для ограниченных роликов будет использоваться только выбранный браузер.",
            "settings.youtubeAccessDisabled": "Cookies браузера отключены, поэтому ограниченные ролики YouTube обычно будут падать с ошибкой.",
            "settings.openYouTube": "Открыть YouTube",
            "settings.subtitles": "Скачивать субтитры, если доступны",
            "settings.audioTracks": "Скачивать дополнительные аудиодорожки, если доступны",
            "settings.close": "Готово",
            "about.title": "О Link2Download",
            "about.app": "Приложение",
            "about.version": "Версия",
            "about.developer": "Разработал",
            "about.website": "Сайт",
            "quality.smart": "Умно",
            "quality.best": "Лучшее",
            "quality.720": "720p",
            "quality.1080": "1080p",
            "quality.4k": "4K",
            "quality.8k": "8K",
            "speed.unlimited": "Безлимитно",
            "speed.50": "50 Мбит/с",
            "speed.25": "25 Мбит/с",
            "speed.10": "10 Мбит/с",
            "speed.4": "4 Мбит/с",
            "transcode.bitrate.auto": "Авто (высокое качество)",
            "toast.invalidURL": "В буфере обмена нет корректного URL.",
            "toast.alreadyQueued": "Эта ссылка уже скачивается или стоит в очереди.",
            "toast.started": "Загрузка началась",
            "toast.debugCopied": "Debug-отчет скопирован в буфер. Вставьте его в чат.",
            "toast.debugFailed": "Не удалось скопировать debug-отчет.",
            "toast.toolMissing": "Не найдены встроенные yt-dlp/ffmpeg.",
            "toast.transcodeVideoOnly": "Транскодирование доступно только для видеофайлов.",
            "toast.transcodeSourceMissing": "Не найден исходный файл для транскодирования.",
            "playlist.prompt.title": "Ссылка относится к плейлисту",
            "playlist.prompt.message": "Скачать только это видео или весь плейлист?",
            "playlist.prompt.single": "Только это видео",
            "playlist.prompt.all": "Весь плейлист",
            "meta.durationUnknown": "длительность неизвестна",
            "meta.noFile": "файл не готов",
            "meta.noSize": "размер неизвестен",
            "meta.failed": "Операция завершилась ошибкой",
            "error.vimeo.linkHint": "Эту ссылку Vimeo нельзя открыть напрямую. Попробуйте ссылку из «Вставить плеер» в Vimeo (player.vimeo.com/video/<id>?h=<token>).",
            "error.interruptedSession": "Эта задача была прервана при прошлом запуске приложения. Нажмите «Повторить», чтобы продолжить.",
            "error.cookies.browserHint": "Link2Download не смог прочитать cookies браузера для этого запроса. Откройте YouTube в поддерживаемом браузере, например в Comet или Chrome, убедитесь, что вы вошли в аккаунт, и повторите попытку.",
            "error.youtube.authHint": "Для этого видео YouTube требует авторизованную сессию браузера. Link2Download умеет автоматически использовать cookies браузера. Убедитесь, что вы вошли в YouTube в Comet, Safari, Chrome, Edge, Chromium или Firefox, и повторите попытку.",
            "error.youtube.formatHint": "YouTube отдал ограниченный список форматов для этого видео. Link2Download уже попробовал совместимые fallback-варианты. Если ошибка повторяется, переключите формат видео на MKV или повторите попытку с другим браузерным профилем.",
            "warn.subtitlesPartial": "Видео загружено, но часть субтитров недоступна.",
            "smart.enabled": "Умные параметры включены.",
            "smart.disabled": "Используются ручные настройки.",
            "smart.help": "Умный режим всегда выбирает максимально доступное качество из источника и автоматически конвертирует видео для Apple/Final Cut: лучшее доступное качество -> Apple MOV.",
            "smart.profileHint": "Любой сервис: максимальное доступное качество -> Apple MOV.",
            "smart.profileHintNoTranscode": "Любой сервис: максимальное качество -> исходный формат (быстрее)."
        ],
        "hi": [
            "app.title": "Link2Download",
            "toolbar.paste": "लिंक पेस्ट करें",
            "toolbar.settings": "सेटिंग्स",
            "toolbar.about": "About",
            "toolbar.debug": "Debug report",
            "toolbar.smart": "स्मार्ट मोड",
            "toolbar.download": "डाउनलोड",
            "toolbar.quality": "क्वालिटी",
            "toolbar.format": "फ़ॉर्मेट",
            "toolbar.saveTo": "सेव पाथ",
            "toolbar.speed": "स्पीड",
            "toolbar.chooseFolder": "चुनें",
            "toolbar.resetDefaults": "डिफ़ॉल्ट रीसेट",
            "toolbar.search": "शीर्षक, लिंक, क्रिएटर खोजें",
            "toolbar.clearSearch": "Clear search",
            "toolbar.clearList": "सूची साफ करें",
            "toolbar.retryErrors": "Retry errors",
            "toolbar.clearErrors": "Clear errors",
            "toolbar.startHint": "समर्थित लिंक पेस्ट करते ही डाउनलोड शुरू होगा।",
            "filter.all": "सभी",
            "filter.video": "वीडियो",
            "filter.audio": "ऑडियो",
            "stats.active": "Active",
            "stats.queued": "Queued",
            "stats.completed": "Completed",
            "stats.failed": "Failed",
            "empty.title": "अभी कोई डाउनलोड नहीं",
            "empty.subtitle": "YouTube, Vimeo, TikTok या Instagram URL पेस्ट करें।",
            "empty.noResultsTitle": "Nothing found",
            "empty.noResultsSubtitle": "Try clearing search or switching filters.",
            "empty.action.resetFilters": "Reset filters",
            "empty.action.paste": "Paste link",
            "empty.action.settings": "Open settings",
            "row.status.queued": "क्यू में",
            "row.status.downloading": "डाउनलोड हो रहा है",
            "row.status.completed": "पूरा",
            "row.status.failed": "विफल",
            "row.status.cancelled": "रद्द",
            "row.status.cancelledHint": "Download was cancelled by user.",
            "progress.preparing": "Preparing download...",
            "progress.downloading": "Downloading...",
            "progress.finalizing": "Finalizing file...",
            "progress.appleOptimize": "Apple के लिए ऑप्टिमाइज़ किया जा रहा है...",
            "progress.appleCopy": "Apple MOV में remux किया जा रहा है...",
            "progress.appleHWTranscode": "Apple MOV के लिए hardware transcode...",
            "progress.appleSWTranscode": "Apple MOV के लिए software transcode...",
            "progress.cookiesRetry": "Retrying with browser cookies",
            "progress.stats.of": "of",
            "progress.stats.total": "Total:",
            "progress.stats.avg": "avg",
            "progress.stats.left": "left",
            "progress.stats.remaining": "left",
            "progress.stats.speed": "speed",
            "progress.stats.eta": "ETA",
            "stage.label": "Stage",
            "stage.preparing": "Preparing",
            "stage.downloading": "Download",
            "stage.remuxing": "Remux",
            "stage.hardwareTranscode": "Hardware transcode",
            "stage.softwareTranscode": "Software transcode",
            "action.showFinder": "Finder में दिखाएँ",
            "action.openFile": "फ़ाइल खोलें",
            "action.copySource": "स्रोत लिंक कॉपी करें",
            "action.openBrowser": "ब्राउज़र में खोलें",
            "action.deleteFile": "फ़ाइल हटाएँ",
            "action.cancel": "रद्द करें",
            "action.retry": "फिर попробовать",
            "action.more": "More",
            "action.removeFromList": "सूची से हटाएँ",
            "details.source": "Source",
            "details.file": "File",
            "details.updated": "Updated",
            "settings.title": "प्राथमिकताएँ",
            "settings.language": "भाषा",
            "settings.system": "सिस्टम",
            "settings.english": "English",
            "settings.russian": "Русский",
            "settings.hindi": "Hindi",
            "settings.chinese": "中文",
            "settings.kind": "डिफ़ॉल्ट डाउनलोड प्रकार",
            "settings.kind.video": "वीडियो",
            "settings.kind.audio": "ऑडियो",
            "settings.quality": "डिफ़ॉल्ट क्वालिटी",
            "settings.videoFormat": "वीडियो फ़ॉर्मेट",
            "settings.audioFormat": "ऑडियो फ़ॉर्मेट",
            "settings.path": "डिफ़ॉल्ट सेव फ़ोल्डर",
            "settings.limit": "स्पीड लिमिट",
            "settings.appleTranscode": "Auto-convert to Apple MOV",
            "settings.appleTranscodeHelp": "Disable to keep source format. Faster and lower CPU usage.",
            "settings.cookies": "ब्राउज़र कुकीज़",
            "cookies.auto": "Auto",
            "cookies.none": "Disabled",
            "settings.youtubeAccessTitle": "YouTube Access",
            "settings.youtubeAccessBody": "Age-restricted and account-only YouTube videos need a signed-in browser session. Link2Download can reuse supported browser cookies, including Comet, when needed.",
            "settings.youtubeAccessAuto": "Auto first tries your default browser, then other installed supported browsers such as Comet, Chrome, Safari, Edge, Chromium, and Firefox.",
            "settings.youtubeAccessSelected": "Only the selected browser will be used for restricted YouTube videos.",
            "settings.youtubeAccessDisabled": "Browser cookies are disabled, so restricted YouTube videos will usually fail.",
            "settings.openYouTube": "Open YouTube",
            "settings.subtitles": "उपलब्ध होने पर सबटाइटल डाउनलोड करें",
            "settings.audioTracks": "उपलब्ध होने पर अतिरिक्त ऑडियो ट्रैक डाउनलोड करें",
            "settings.close": "Done",
            "about.title": "About Link2Download",
            "about.app": "Application",
            "about.version": "Version",
            "about.developer": "Developer",
            "about.website": "Website",
            "quality.smart": "Smart",
            "quality.best": "Best",
            "quality.720": "720p",
            "quality.1080": "1080p",
            "quality.4k": "4K",
            "quality.8k": "8K",
            "speed.unlimited": "Unlimited",
            "speed.50": "50 Mbps",
            "speed.25": "25 Mbps",
            "speed.10": "10 Mbps",
            "speed.4": "4 Mbps",
            "toast.invalidURL": "क्लिपबोर्ड में वैध URL नहीं है।",
            "toast.alreadyQueued": "यह लिंक पहले से डाउनलोड हो रहा है या कतार में है।",
            "toast.started": "डाउनलोड शुरू",
            "toast.debugCopied": "Debug report copied to clipboard. Paste it in chat.",
            "toast.debugFailed": "Failed to copy debug report to clipboard.",
            "toast.toolMissing": "Bundled yt-dlp/ffmpeg नहीं मिला।",
            "playlist.prompt.title": "यह लिंक किसी प्लेलिस्ट का हिस्सा है",
            "playlist.prompt.message": "केवल यह वीडियो डाउनलोड करना है या पूरी प्लेलिस्ट?",
            "playlist.prompt.single": "सिर्फ यह वीडियो",
            "playlist.prompt.all": "पूरी प्लेलिस्ट",
            "meta.durationUnknown": "अवधि अज्ञात",
            "meta.noFile": "फ़ाइल लंबित",
            "meta.noSize": "आकार अज्ञात",
            "meta.failed": "कार्य विफल",
            "error.vimeo.linkHint": "This Vimeo link cannot be opened directly. Use the Vimeo embed/player link (player.vimeo.com/video/<id>?h=<token>).",
            "error.interruptedSession": "This job was interrupted when the app was restarted. Retry to continue.",
            "error.cookies.browserHint": "Link2Download could not read browser cookies for this request. Open YouTube in a supported browser such as Comet or Chrome, confirm you are signed in, then retry.",
            "error.youtube.authHint": "YouTube requires an authorized browser session for this video. Link2Download can use your browser cookies automatically. Make sure you are signed in to YouTube in Comet, Safari, Chrome, Edge, Chromium, or Firefox, then retry.",
            "error.youtube.formatHint": "YouTube exposed a restricted format list for this video. Link2Download already tried compatible fallbacks. If it still fails, switch the video format to MKV or retry with another browser profile.",
            "warn.subtitlesPartial": "वीडियो डाउनलोड हुआ, लेकिन कुछ सबटाइटल उपलब्ध नहीं थे।",
            "smart.enabled": "Smart defaults enabled.",
            "smart.disabled": "Manual settings enabled.",
            "smart.help": "Smart mode हर source से highest available quality चुनता है और वीडियो को Apple/Final Cut compatible MOV में कन्वर्ट करता है: best available quality -> Apple MOV.",
            "smart.profileHint": "Any service: best available quality -> Apple MOV.",
            "smart.profileHintNoTranscode": "Any service: best available quality -> source format (faster)."
        ],
        "zh": [
            "app.title": "Link2Download",
            "toolbar.paste": "粘贴链接",
            "toolbar.settings": "设置",
            "toolbar.about": "关于",
            "toolbar.debug": "调试报告",
            "toolbar.smart": "智能模式",
            "toolbar.download": "下载类型",
            "toolbar.quality": "画质",
            "toolbar.format": "格式",
            "toolbar.saveTo": "保存到",
            "toolbar.speed": "速度",
            "toolbar.chooseFolder": "选择",
            "toolbar.resetDefaults": "恢复默认",
            "toolbar.search": "按标题、链接、作者搜索",
            "toolbar.clearSearch": "清空搜索",
            "toolbar.clearList": "清空列表",
            "toolbar.retryErrors": "重试错误项",
            "toolbar.clearErrors": "清除错误项",
            "toolbar.startHint": "粘贴支持的链接后会自动开始下载。",
            "filter.all": "全部",
            "filter.video": "视频",
            "filter.audio": "音频",
            "stats.active": "进行中",
            "stats.queued": "排队",
            "stats.completed": "完成",
            "stats.failed": "失败",
            "empty.title": "暂无下载",
            "empty.subtitle": "粘贴 YouTube、Vimeo、TikTok 或 Instagram 链接。",
            "empty.noResultsTitle": "未找到内容",
            "empty.noResultsSubtitle": "请尝试清空搜索或重置筛选。",
            "empty.action.resetFilters": "重置筛选",
            "empty.action.paste": "粘贴链接",
            "empty.action.settings": "打开设置",
            "row.status.queued": "排队中",
            "row.status.downloading": "下载中",
            "row.status.completed": "已完成",
            "row.status.failed": "失败",
            "row.status.cancelled": "已取消",
            "row.status.cancelledHint": "下载已由用户取消。",
            "progress.preparing": "正在准备下载...",
            "progress.downloading": "正在下载...",
            "progress.finalizing": "正在完成文件处理...",
            "progress.appleOptimize": "正在为 Apple 优化...",
            "progress.appleCopy": "正在重封装为 Apple MOV...",
            "progress.appleHWTranscode": "正在用硬件转码为 Apple MOV...",
            "progress.appleSWTranscode": "正在用软件转码为 Apple MOV...",
            "progress.cookiesRetry": "正在使用浏览器 Cookies 重试",
            "progress.stats.of": "共",
            "progress.stats.total": "总计：",
            "progress.stats.avg": "平均",
            "progress.stats.left": "剩余",
            "progress.stats.remaining": "还需",
            "progress.stats.speed": "速度",
            "progress.stats.eta": "预计",
            "stage.label": "阶段",
            "stage.preparing": "准备中",
            "stage.downloading": "下载中",
            "stage.remuxing": "重封装",
            "stage.hardwareTranscode": "硬件转码",
            "stage.softwareTranscode": "软件转码",
            "action.showFinder": "在 Finder 中显示",
            "action.openFile": "打开文件",
            "action.copySource": "复制源链接",
            "action.openBrowser": "在浏览器中打开",
            "action.deleteFile": "删除文件",
            "action.cancel": "取消",
            "action.retry": "重试",
            "action.more": "更多",
            "action.removeFromList": "从列表移除",
            "details.source": "来源",
            "details.file": "文件",
            "details.updated": "更新时间",
            "settings.title": "偏好设置",
            "settings.language": "语言",
            "settings.system": "跟随系统",
            "settings.english": "English",
            "settings.russian": "Русский",
            "settings.hindi": "Hindi",
            "settings.chinese": "中文",
            "settings.kind": "默认下载类型",
            "settings.kind.video": "视频",
            "settings.kind.audio": "音频",
            "settings.quality": "默认画质",
            "settings.videoFormat": "视频格式",
            "settings.audioFormat": "音频格式",
            "settings.path": "默认保存目录",
            "settings.limit": "限速",
            "settings.appleTranscode": "自动转为 Apple MOV",
            "settings.appleTranscodeHelp": "关闭后将保留源格式，不再转成 Apple MOV。速度更快，CPU 占用更低。",
            "settings.cookies": "浏览器 Cookies",
            "cookies.auto": "自动",
            "cookies.none": "关闭",
            "settings.youtubeAccessTitle": "YouTube 访问",
            "settings.youtubeAccessBody": "受年龄限制或仅限账号访问的 YouTube 视频需要已登录的浏览器会话。Link2Download 会在需要时复用受支持浏览器的 Cookies，包括 Comet。",
            "settings.youtubeAccessAuto": "自动模式会先尝试默认浏览器，再尝试其他已安装且受支持的浏览器，包括 Comet、Chrome、Safari、Edge、Chromium 和 Firefox。",
            "settings.youtubeAccessSelected": "受限视频只会使用当前选中的浏览器。",
            "settings.youtubeAccessDisabled": "浏览器 Cookies 已关闭，因此受限 YouTube 视频通常会下载失败。",
            "settings.openYouTube": "打开 YouTube",
            "settings.subtitles": "可用时下载字幕",
            "settings.audioTracks": "可用时下载额外音轨",
            "settings.close": "完成",
            "about.title": "关于 Link2Download",
            "about.app": "应用",
            "about.version": "版本",
            "about.developer": "开发者",
            "about.website": "网站",
            "quality.smart": "智能",
            "quality.best": "最佳",
            "quality.720": "720p",
            "quality.1080": "1080p",
            "quality.4k": "4K",
            "quality.8k": "8K",
            "speed.unlimited": "不限速",
            "speed.50": "50 Mbps",
            "speed.25": "25 Mbps",
            "speed.10": "10 Mbps",
            "speed.4": "4 Mbps",
            "toast.invalidURL": "剪贴板中没有有效链接。",
            "toast.alreadyQueued": "该链接已在下载或排队中。",
            "toast.started": "下载已开始",
            "toast.debugCopied": "调试报告已复制到剪贴板，请粘贴到聊天中。",
            "toast.debugFailed": "复制调试报告到剪贴板失败。",
            "toast.toolMissing": "未找到内置 yt-dlp/ffmpeg。",
            "playlist.prompt.title": "该链接属于播放列表",
            "playlist.prompt.message": "只下载这个视频，还是下载整个播放列表？",
            "playlist.prompt.single": "仅此视频",
            "playlist.prompt.all": "整个播放列表",
            "meta.durationUnknown": "时长未知",
            "meta.noFile": "文件待生成",
            "meta.noSize": "大小未知",
            "meta.failed": "操作失败",
            "error.vimeo.linkHint": "该 Vimeo 链接无法直接下载。请使用 Vimeo 的嵌入/播放器链接（player.vimeo.com/video/<id>?h=<token>）。",
            "error.interruptedSession": "该任务在上次应用重启时被中断。请重试以继续。",
            "error.cookies.browserHint": "Link2Download 无法读取这次请求所需的浏览器 Cookies。请先在受支持的浏览器中打开 YouTube，例如 Comet 或 Chrome，并确认已登录，然后重试。",
            "error.youtube.authHint": "此视频需要已登录的浏览器会话。Link2Download 可以自动使用你的浏览器 Cookies。请先在 Comet、Safari、Chrome、Edge、Chromium 或 Firefox 中登录 YouTube，然后重试。",
            "error.youtube.formatHint": "YouTube 为此视频返回了受限的格式列表。Link2Download 已尝试兼容的回退方案。如果仍然失败，请把视频格式切换为 MKV，或换一个浏览器配置重试。",
            "warn.subtitlesPartial": "视频已下载，但部分字幕不可用。",
            "smart.enabled": "已启用智能默认设置。",
            "smart.disabled": "已启用手动设置。",
            "smart.help": "智能模式会始终选择来源中可用的最高画质，并自动转换为 Apple/Final Cut 兼容 MOV：最高可用画质 -> Apple MOV。",
            "smart.profileHint": "任何平台：最高可用画质 -> Apple MOV。",
            "smart.profileHintNoTranscode": "任何平台：最高可用画质 -> 源格式（更快）。"
        ]
    ]

    static func localize(_ key: String, language: AppLanguage) -> String {
        let resolved = resolvedCode(for: language)
        if let value = strings[resolved]?[key] {
            return value
        }
        if let fallback = strings["en"]?[key] {
            return fallback
        }
        return key
    }

    static func resolvedCode(for language: AppLanguage) -> String {
        switch language {
        case .system:
            let code = Locale.preferredLanguages.first ?? "en"
            if code.hasPrefix("ru") { return "ru" }
            if code.hasPrefix("hi") { return "hi" }
            if code.hasPrefix("zh") { return "zh" }
            return "en"
        default:
            return language.code
        }
    }
}
